name: app
publish_to: none
version: 0.0.1+1
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  components:
  core:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
