name: App Distribution (iOS)

on:
  workflow_dispatch:

env:
  # Android: packageName, iOS: bundleIdentifier
  PACKAGE_ID: any.example.app.id

  # Firebase AppDistribution で配信するグループ名
  DISTRIBUTION_GROUPS: internal_tester

  SEND_SYMBOLS_TO_CRASHLYTICS: true

# このActionsで必要なSecretsは以下の通りです
# - KEYSTORE_BASE64: keystore.jks (base64 encode)
# - KEYSTORE_PASSWORD: keystore.jks のパスワード
# - KEY_ALIAS: keystore.jks のエイリアス
# - KEY_PASSWORD: keystore.jks のエイリアスのパスワード
# - FIREBASE_APP_ID_ANDROID_PRODUCTION: Firebase App ID (Production)
# - CREDENTIAL_FILE_CONTENT: Firebase App Distribution 用のサービスアカウントキー

jobs:
  deploy_store_google_play:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-flutter-env

      # アプリのビルドに利用する証明書を設定します。
      - name: Setup Certificates
        working-directory: packages/app
        run: |
          mkdir -p $HOME/keystores
          # echo "{{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $HOME/keystores/release.keystore

      - name: Build
        working-directory: packages/app
        id: build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --release --no-tree-shake-icons --obfuscate --split-debug-info=obfuscate/android
      
      - name: Find Binary
        id: binary_path
        run: echo "binary_path=$(find . -name '*.apk' | grep 'flutter-apk')" >> $GITHUB_OUTPUT
      
      # Crashlytics にシンボルをアップロードします。
      - name: Send Symbols to Crashlytics If Need
        if: ${{ env.SEND_SYMBOLS_TO_CRASHLYTICS }} 
        working-directory: packages/app
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_ANDROID_PRODUCTION }}
        run: |
          npm install -g firebase-tools
          firebase crashlytics:symbols:upload --app=$FIREBASE_APP_ID obfuscate/android

      - name: Deploy To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID_PRODUCTION }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: ${{ env.DISTRIBUTION_GROUPS }}
          file: ${{ steps.build.outputs.binary_path }}
